### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by LiUzHiAn** [ae-foster/pytorch-simclr#5]
Hi, I met this error via executing `python3 simclr.py --num-epochs 1000 --cosine-anneal --filename output.pth --base-lr 1.5`. It seems it was caused by the LARS in `torchlars`. Below is my packages version:
```python
numpy==1.18.1 
torchvision==0.6.0a0+35d732a 
pillow==8.2.0 
torchlars==0.1.2
tqdm==4.45.0
torch==1.5.1
```
And here is my traceback:
```python
==> Preparing data..
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
==> Building model..

Epoch: 0
Loss: ****           | 0/782 [00:00<?, ?it/s]Warning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (operator() at /opt/conda/conda-bld/pytorch_1591914742272/work/torch/csrc/utils/python_arg_parser.cpp:756)
Loss: ****           | 0/782 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "/home/liuzhian/anaconda3/envs/pt1.5/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/liuzhian/anaconda3/envs/pt1.5/lib/python3.6/site-packages/torchlars/lars.py", line 98, in hide_weight_decays
    yield weight_decays
  File "/home/liuzhian/anaconda3/envs/pt1.5/lib/python3.6/site-packages/torchlars/lars.py", line 145, in step
    self.apply_adaptive_lrs(weight_decays)
  File "/home/liuzhian/anaconda3/envs/pt1.5/lib/python3.6/site-packages/torchlars/lars.py", line 140, in apply_adaptive_lrs
    p.grad.add_(weight_decay, p.data)
RuntimeError: CUDA error: invalid device function

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

Any idea to fix that? Thanks in advance!

**Comment by ae-foster** [comment]
Hi @LiUzHiAn , thanks for reporting this error.

I'm afraid that looks like a `torchlars` issue - you might try reporting it their repo https://github.com/kakaobrain/torchlars.

For now, you could simply train SimCLR with SGD by commenting out this line https://github.com/ae-foster/pytorch-simclr/blob/dc9ac57a35aec5c7d7d5fe6dc070a975f493c1a5/simclr.py#L99
and insteading putting `encoder_optimizer = base_optimizer`

You might need to tweak the learning rate with SGD. Hope that helps!

**Comment by LiUzHiAn** [comment]
Yeah, it works in this way. Not very familiar with `torchlars`, I'll try with SGD
